; G-code generated by TurtleStitch
; Stitches: 8
; Size: 20.0mm x 12.0mm
; Color changes: 1
G21 ; millimeters
G90 ; absolute positioning
; color r:0 g:0 b:0
G0 X0.000 Y0.000
G1 Z5.000
G1 X4.000 Y0.000
G1 Z10.000
G1 X8.000 Y0.000
G1 Z15.000
G0 X16.000 Y8.000
G1 Z20.000
G1 X20.000 Y12.000
G1 Z25.000
; color r:230 g:80 b:65
COLOR_CHANGE
G1 Z30.000
G1 X16.000 Y12.000
G1 Z35.000
G1 X12.000 Y12.000
G1 Z40.000
M400 ; wait for moves to finish
; Total Z travel: 40.0mm
