; G-code generated by TurtleStitch
; Stitches: 5
; Size: 20.0mm x 12.0mm
G21 ; millimeters
G90 ; absolute positioning
G0 X0.000 Y0.000
G1 X4.000 Y0.000
G1 Z5.000
G1 X8.000 Y0.000
G1 Z10.000
G0 X16.000 Y8.000
G1 X20.000 Y12.000
G1 Z15.000
G1 X16.000 Y12.000
G1 Z20.000
G1 X12.000 Y12.000
G1 Z25.000
M400 ; wait for moves to finish
M84 ; disable motors
; Total Z travel: 25.0mm
